# yq script file used to update the Jekyll config file of https://github.com/jeandeaual/lilypond-jekyll-template
# See https://mikefarah.gitbook.io/yq/commands/write-update#using-a-script-file-to-update
- command: update
  path: title
  value: “Pretender” by Official Hige Dandism
# Use the short description from the GitHub project
- command: delete
  path: description
- command: update
  path: baseurl
  value: /lilypond-band-official-hige-dandism-pretender
- command: update
  path: repository
  value: jeandeaual/lilypond-band-official-hige-dandism-pretender
- command: update
  path: copyright
  value: true
